import Head from "next/head";
import { BackgroundBubbles } from "./components/BackgroundBubbles";
import { Inter } from "@next/font/google";

const inter = Inter({ weight: ["400", "500"], subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Yusufbek Alimatov - Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <BackgroundBubbles />
      </main>
    </>
  );
}
