name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: "Build and deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch changes
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm install

      - name: Build next app
        run: npm run build

      - name: Create static files
        run: npm run export

      - uses: aws-actions/configure-aws-credentials@v6.0.0
        name: "AWS Configuration"
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: "Deploy to S3"
        run: aws s3 sync out ${{ secrets.AWS_S3_BUCKET }}

      - name: "Cloudfront invalidation"
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"
